---
- name: Performance profiling
  hosts: localhost
  become: false #required to run cgexec on localhost
  tasks:
    - name: Install cgroup tools
      yum:
        name: libcgroup-tools
        state: present
      become: true #required so that package can be installed 

    - name: Create ex447-stats group
      shell: cgcreate -a ansible:ansible -t ansible:ansible -g cpuacct,memory,pids:ex447_stats
      become: true #required to be executed as root and not use sudo in shell command

    - name: Perform profiling
      shell: cgexec -g cpuacct,memory,pids:ex447_stats ansible-playbook package.yml
      register: output

    - name: Show profiling
      debug:
        var: output.stdout_lines
